Update frFR.lua for 0.2.0
Peterodox/YUI-Dialogue pull request #6
Opened 2024-03-25 15:37 UTC by Zazou89

😉

2024-03-25 17:10 UTC, Brainc3ll requested changes
Salut, merci pour les corrections et l'amélioration de la trad

J'allais changer ceci :

L["Press Button To Scroll Down"] = "Appuyer sur le bouton fait défiler vers le bas";

et pour la cohérence de la trad:

L["Quest Item Display"] = "Afficher l'objet de quête"; --better translate ?

L["Quest Item Display Hide Seen"] = "Ignorer les objets déjà vus"; --better translate ?
L["Quest Item Display Hide Seen Desc"] = "Ignore les objets qui ont déjà été découverts par l'un de vos personnages.";

2024-03-25 17:14 UTC, Zazou89 commented
Oui tes changements sont mieux :D, tu fais un PR ou je mets à jour ?

2024-03-25 17:18 UTC, Brainc3ll commented
Merci ;)

Je te laisse update ;)

2024-03-25 17:18 UTC, Zazou89 commented
Ah ! J'ai vu que tu as fais des review, mais je sais pas comment les accepter 😅

2024-03-25 17:25 UTC, Brainc3ll commented
Désolé, je me perd un peu avec github, je n'ai pas l'habitude.

2024-03-26 16:52 UTC, Peterodox commented
Thank you all :)

2024-03-26 16:53 UTC, merged